tipus_index:
    path:     /
    defaults: { _controller: "GestorDeProjectesBundle:Tipus:index" }
    methods:  GET

tipus_show:
    path:     /{id}/show
    defaults: { _controller: "GestorDeProjectesBundle:Tipus:show" }
    methods:  GET

tipus_new:
    path:     /new
    defaults: { _controller: "GestorDeProjectesBundle:Tipus:new" }
    methods:  [GET, POST]

tipus_edit:
    path:     /{id}/edit
    defaults: { _controller: "GestorDeProjectesBundle:Tipus:edit" }
    methods:  [GET, POST]

tipus_delete:
    path:     /{id}/delete
    defaults: { _controller: "GestorDeProjectesBundle:Tipus:delete" }
    methods:  DELETE
